### ISSUE TITLE
[BUG] Shell navigation not working in markup

### ISSUE THREAD

**Issue by hulluP** [CommunityToolkit/Maui.Markup#214] opened 2023-04-19 07:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui.Markup/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I register routes for more than two level, when navigating back from the third level it always jumps to root page.
this is for "normal" navigation and modal pages

### Expected Behavior

Following the docs on https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation?view=net-maui-7.0

when calling 
`
	var route = $"..";
	return Shell.Current.GoToAsync(route);
`
from the ModalPage or the 2ndLevelPage in both cases it should pop the page of the stack and show NewsDetailPage

### Steps To Reproduce

to reproduce:

- pull https://github.com/hulluP/MauiShellNavigation
- run in iOs or Android
- click on any of the article entries on the NewsPage
- click on the "Launch 2nd Level" button
- click on close me -> this should not jump back to Newspage it should jump to Detail page
- click on any of the article entries on the NewsPage
- click on the "Launch Modal" button
- click on close me -> this should not jump back to Newspage it should jump to Detail page

### Link to public reproduction project repository

https://github.com/hulluP/MauiShellNavigation

### Environment

```markdown
- .NET MAUI C# Markup CommunityToolkit: 3.1.0
- 
- OS: 
   - iOS 14.2
   - Android 21
- .NET MAUI: 5.0.0
```

**Comment by brminnick** [comment] 2023-04-19 18:19
Hi @hulluP! I'm having trouble understanding how this bug is related to `CommunityToolkit.Maui.Markup`. 

I confirm the behavior in the sample app you've provided. But Shell and Shell Navigation are not using any features from `CommunityToolkit.Maui.Markup`.

Have you confirmed this same bug in an app without `CommunityToolkit.Maui.Markup`? 

My hunch is that this is either a .NET MAUI bug, or a bug in your sample caused by incorrectly initializing Shell routes.

I am 99% certain that this bug is not caused by `CommunityToolkit.Maui.Markup`.

**Comment by brminnick** [comment] 2023-04-19 18:20
Closing for now. 

I'm happy to re-open it if a sample can be provided that demonstrates this bug is specific to `CommunityToolkit.Maui.Markup`.

**Closed by brminnick** 2023-04-19 18:20 UTC
Labels: bug, unverified
