### ISSUE TITLE
[Bug] Refresh view is off the screen

### ISSUE THREAD

**Issue by ss-proc** [CommunityToolkit/Maui.Markup#108] opened 2022-09-04 05:59 UTC
### Description

Hi, I'm a newbie trying to learn Markup. I cloned the https://github.com/CommunityToolkit/Maui.Markup/tree/main/samples and ran it on iOS simulator on macOS M1, I noticed that the refresh view is off the screen. Also when I set the new count to "1" then the news list is also off the screen.

### Stack Trace

N/A

### Link to Reproduction Sample

https://github.com/CommunityToolkit/Maui.Markup/tree/main/samples

### Steps to Reproduce

Please see above

### Expected Behavior

- Refresh view control is in the center
- When news settings count = 1, the first news should be in the center
- When news count = 2, the view should show 2 items

### Actual Behavior

https://user-images.githubusercontent.com/104405893/188299721-aba3f1b5-3a32-40a9-984a-61390616747f.mov

### Basic Information

```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: arm64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

### Reproduction imagery

<img width="617" alt="Screen Shot 2022-09-03 at 10 49 42 PM" src="https://user-images.githubusercontent.com/104405893/188299698-cec02a59-c666-466b-a4e3-a20eaac4ce7d.png">

**Comment by brminnick** [comment] 2022-09-05 22:50
Thanks @ss-proc! 

I confirmed that this is a .NET MAUI bug:
https://github.com/dotnet/maui/issues/7315

I'll close this for now since the Issue isn't specific to `CommunityToolkit.Maui.Markup`

**Closed by brminnick** 2022-09-05 22:50 UTC
Labels: bug, unverified
